name: focus_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  table_calendar: ^3.0.9
  uuid: ^4.3.3
  # Package DND dihapus karena error, fitur diblokir sementara.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Package untuk generate Icon & Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

# KONFIGURASI YANG BENAR:
flutter_launcher_icons:
  android: "ic_launcher" # <--- UBAH INI DARI "launcher_icon" KE "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# Konfigurasi Splash Screen
flutter_native_splash:
  color: "#121212"
  image: "assets/icon/icon.png"
  android_12:
    image: "assets/icon/icon.png"
    color: "#121212"
  ios: true
  android: true
